site_name: Knit
site_description: Documentation for Knit
site_author: Stephen Leitnick
site_url: https://sleitnick.github.io/Knit/
repo_url: https://github.com/Sleitnick/Knit
repo_name: Knit
copyright: Copyright &copy; 2020 - 2021 Stephen Leitnick

nav:
  - Home: index.md
  - Why Knit: whyknit.md
  - Getting Started: gettingstarted.md
  - Services: services.md
  - Controllers: controllers.md
  - Util: 
    - Component: util/component.md
    - Janitor: util/janitor.md
    - Option: util/option.md
    - Promise: util/promise.md
    - RemoteSignal: util/remotesignal.md
    - RemoteProperty: util/remoteproperty.md
    - Signal: util/signal.md
    - Streamable: util/streamable.md
    - StreamableUtil: util/streamableutil.md
    - TableUtil: util/tableutil.md
    - Timer: util/timer.md
  - Knit API: knitapi.md
  - Execution Model: executionmodel.md
  - VS Code Snippets: vscodesnippets.md
  - Examples: examples.md
  - Style Guide: styleguide.md

theme:
  logo: "img/logo.png"
  favicon: "img/favicon.png"
  name: material
  font:
    text: Ubuntu
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
  highlightjs: true
  hljs_languages:
    - lua

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Sleitnick/Knit
      name: GitHub repository for Knit
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Sleitnick
      name: Twitter for Knit's author

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
