site_name: Knit
site_description: Documentation for Knit
site_author: Stephen Leitnick
site_url: https://sleitnick.github.io/Knit/
repo_url: https://github.com/Sleitnick/Knit
repo_name: Knit
copyright: Copyright &copy; 2020 - 2021 Stephen Leitnick

nav:
  - Home: index.md
  - Why Knit: whyknit.md
  - Getting Started: gettingstarted.md
  - Services: services.md
  - Controllers: controllers.md
  - Util: util.md
  - Knit API: knitapi.md
  - Execution Model: executionmodel.md
  - VS Code Snippets: vscodesnippets.md
  - Examples: examples.md
  - Style Guide: styleguide.md

theme:
  logo: "img/logo.png"
  favicon: "img/favicon.png"
  name: material
  font:
    text: Ubuntu
    code: Roboto Mono
  palette:
    primary: indigo
    accent: light blue
  highlightjs: true
  hljs_languages:
    - lua

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Sleitnick/Knit
      name: GitHub repository for Knit
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sleitnick
      name: Twitter for Knit's author

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
