[package]
name = "sleitnick/knit"
description = "Knit is a lightweight game framework"
version = "1.3.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "sleitnick/comm@0.2"
Promise = "evaera/promise@3.1"
