[package]
name = "sleitnick/knit"
description = "Knit is a lightweight game framework"
version = "1.4.7"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "sleitnick/comm@^0.3"
Promise = "evaera/promise@^4"
