[package]
name = "sleitnick/knit"
description = "Knit is a lightweight game framework"
version = "1.1.0-rc.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "sleitnick/comm@^0.1"
Promise = "evaera/promise@^3.1"
