[package]
name = "sleitnick/knit-bundle"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "sleitnick/comm@^0.3"
Component = "sleitnick/component@^2"
EnumList = "sleitnick/enum-list@^2"
Input = "sleitnick/input@^1"
Option = "sleitnick/option@^1"
Signal = "sleitnick/signal@^1"
Streamable = "sleitnick/streamable@^1"
TableUtil = "sleitnick/table-util@^1"
Timer = "sleitnick/timer@^1"
Trove = "sleitnick/trove@^0.4"
Loader = "sleitnick/loader@2.0.0"
Promise = "evaera/promise@^4"
