name: Release

on:
  push:
    tags:
      - 'v*'
  
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install foreman
        uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ SECRETS.GITHUB_TOKEN }}
      - name: Build project
        run: |
          mkdir -p Knit
          cp -R src/* Knit
          zip -r knit.zip Knit/**
      - name: Build place file
        run: |
          rojo build publish.project.json -o Knit.rbxl
          rojo build default.project.json -o Knit.rbxm
      - name: Publish Knit to Roblox
        shell: bash
        env:
          REMODEL_AUTH: ${{ secrets.RBX_AUTH }}
        run: |
          remodel run publish.lua
      - name: Changelog
        run: |
          python3 last_changelog.py > log.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref }}
          body_path: log.md
          fail_on_unmatched_files: true
          files: |
            knit.zip
            Knit.rbxm
