name: Release

on:
  push:
    tags:
      - 'v*'
  
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Publish release to Wally
        shell: bash
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
        run: |
          mkdir -p ~/.wally
          echo "$WALLY_AUTH" > ~/.wally/auth.toml
          cd src
          rm -rf Packages
          wally publish
          cd ..
      - name: Wally install
        run: |
          cd src
          rm wally.toml
          mv wally_bundle.toml wally.toml
          wally install
          cd ..
      - name: Build place file
        run: |
          rojo build publish.project.json -o Knit.rbxl
      - name: Publish Knit to Roblox
        shell: bash
        env:
          REMODEL_AUTH: ${{ secrets.RBX_AUTH }}
        run: |
          remodel run publish.lua
      - name: Get version
        id: get_version
        # run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Changelog
        run: python3 last_changelog.py CHANGELOG.md > log.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body_path: log.md
          fail_on_unmatched_files: true
          files: |
            Knit.rbxm
